### ISSUE TITLE
How stable and usable is this compat library?

### ISSUE THREAD

**Issue by gonzalomelov** [chrisanderson79/MediaBrowserCompat#1]
Hi!

I haven't yet tried this, also I haven't looking at the source code, but can you please tell me how advanced is this MediaBrowserCompat?

Thanks

**Comment by ichrisanderson** [comment]
It should be working with the universal media sample https://goo.gl/GZF3Qd I'm currently not aware of any issues with it, but it was just put together to provide a backward port of the official sample. If there's been any updates to the system mediabrowser then you'd need to update the compat package.

**Comment by gonzalomelov** [comment]
Okay, great! I will look at the sample and include it on my project. Thanks!
